# MQTT Broker Configuration avec TLS

listener 1883
allow_anonymous true

listener 8883
allow_anonymous true
certfile /certs/server.crt
keyfile /certs/server.key
cafile /certs/ca.crt



# Logs
log_type all
log_timestamp true